---
title: "Lab 4 Final"
author: "Harshini Karthikeyan"
date: "December 3, 2022"
mainfont: "Times New Roman"
format: 
  html:
    code-fold: true
    code-summary: "Show code"
    monobackgroundcolor: lightsteelblue
    backgroundcolor: whitesmoke
    fontcolor: steelblue
    self-contained: true
execute: 
  warning: false
  message: false
editor: visual
theme: zephyr
---

# Lab 4

```{r setup}
library(tidyverse)
```

```{r here}
avocado <- read.csv(here::here("supporting_artifacts",
                                    "Labs", "Lab_4_Final",
                               "avocado.csv"))
```

1.  desc dataset:

```{r learn about data}
str(avocado)
dim(avocado)
avocado |> distinct(region)
```

### Region Data sets

```{r region datasets}
region_data <- 
  data.frame(region = c("California", "Midsouth", "Northeast", 
                        "Philadelphia",
                        "SouthCentral", "Southeast", "Plains",
                        "GreatLakes", "GrandRapids",
                        "NorthernNewEngland", "SouthCarolina" ))
metro_data <- 
  data.frame(region = c("BaltimoreWashington", "BuffaloRochester", 
                        "RaleighGreensboro", "RichmondNorfolk",
                        "PhoenixTucson", "CincinnatiDayton",
                        "DallasFtWorth", "HartfordSpringfield", 
                        "HarrisburgScranton", "MiamiFtLauderdale", 
                        "NewOrleansMobile"))
totalUS_data <-
  data.frame(region = c("TotalUS"))
```

### Semi Joins

```{r semi joins}
avocado <- anti_join(avocado, totalUS_data, by = "region")

avocado_region <- avocado

avocado_region <- 
  semi_join(avocado_region, region_data, by = "region")

avocado_metro <- avocado

avocado_metro <- 
  semi_join( avocado_metro,  metro_data, by = "region")
  

```

3.  SouthCentral

```{r}
avocado_region|> filter(year == "2017", ) |>
  slice_max(order_by = X4046, n = 1 )
```
