---
title: "Preview Activity Cereal"
author: "Harshini Karthikeyan"
date: "December 3, 2022"
mainfont: "Times New Roman"
format: 
  html:
    self-contained: true
execute:
  message: false
  warning: false
editor: visual
---

## 

```{r setup}
#| warning: false
#| message: false

library(tidyverse)
```

```{r 1}
cereals <- 
  read.csv(here::here("supporting_artifacts",
                                    "Activities",
                                 "Preview_Activity_Cereal",
                       "cereal.csv"))

cereals_long <- cereals |> 
  pivot_longer(cols = c(fat, fiber, protein), 
         names_to = "Nutrient",
         values_to = "Amount") |> 
  select(Name = name, Nutrient, Amount)
cereals_long

```

You can add options to executable code like this

```{r data set}
prof_info <- data.frame(
  professor = 
    c("Bodwin", "Glanz", "Carlton", "Sun", "Theobold"),
  undergrad_school = 
    c("Harvard", "Cal Poly", "Berkeley", "Harvard", "Colorado Mesa University"),
  grad_school = 
    c("UNC", "Boston University", "UCLA", "Stanford", "Montana State University")
)

prof_course <- data.frame(
  professor = c("Bodwin", "Glanz", "Carlton", "Theobold"),
  Stat_331 = c(TRUE, TRUE, TRUE, TRUE),
  Stat_330 = c(FALSE, TRUE, TRUE, FALSE),
  Stat_431 = c(TRUE, TRUE, FALSE, TRUE)
)

course_info <- data.frame(
  course = c("Stat_331", "Stat_330", "Stat_431"),
  num_sections = c(8, 3, 1)
)
```

```{r right join}
prof_classes <- prof_info |>
  right_join(prof_course, by = "professor")
  
```

```{r full join}
prof_info |> full_join(prof_course, by = "professor")
```

```{r}
prof_course |> 
  pivot_longer(cols = c(Stat_331, Stat_330, Stat_431),
               names_to = "course", values_to = "can_teach") |>
  right_join(course_info, by = "course")
```
